<div class="contentBox height500">
    <div class="contentBox width325">
        <div  class="ui-dialog-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">Change Password</div>
        <div id="errorHelper" class="ui-state-error ui-helper-hidden"><span class="ui-state-error-text">errr</span></div>
        <div class="contentBox">
            <div>
                <span class="width105">Actual:</span>
                <input type="password" id="current" name="current" maxlength="50" size="15" value=""/>
            </div>
            <div>
                <span class="width105">Nuevo:</span>
                <input type="password" id="new" name="new" maxlength="50" size="15" value=""/>
            </div>
            <div>
                <span class="width105">Confirmar:</span>
                <input type="password" id="confirm" name="confirm" maxlength="50" size="15" value=""/>
            </div>
            <div class="center_align">
                <button id="buttonchange" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="changePasword()"><span class="ui-button-text">Cambiar</span></button></div>
        </div>
    </div>
</div>