
<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/jquery.autocomplete.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/jqModal.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/scripts/printjs/print.min.css');

$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/jquery/jquery.poloche.block.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/jquery/jquery.numeric.js');
//$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/jquery/jquery.autocomplete.pack.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/jquery/jquery.hotkeys.min.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/jquery/jquery.jsonp-2.1.4.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/printjs/print.min.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/libs/recepcion.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/libs/entrega.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/scripts/printervue/printvue.js');
?>
<?php
$session = Zend_Registry::get(App_Util_Statics::$SESSION);
?>
<script type="text/javascript">
    var arrayDefault = <?= $this->predef ?>;
    var clientesDefault = <?= $this->clientes ?>;
    var userSucursal = <?= $this->userSucursal ?>;
    var userCiudadID = "<?= $this->idCiudadOrigen ?>";
    var defaultConfig = <?= Zend_Json::encode($session->configSYS) ?>;
    var SYS_CONFIG = <?= $this->configuraciones ?>;    
    var eventsFromDB = <?= Zend_Json::encode($this->events) ?>;
//    console.log(events);
    events = MergeRecursive(events,eventsFromDB);//$.extend({}, events, eventsFromDB);

</script>
<?php
$session = Zend_Registry::get(App_Util_Statics::$SESSION);
?>
<APPLET name="printerSystem" 
        archive="<?= $this->baseUrl(); ?>/PrintDocEncomienda.jar, <?= $this->baseUrl(); ?>/lib/core-3.1.0.jar, <?= $this->baseUrl(); ?>/lib/javase-2.0-SNAPSHOT.jar, <?= $this->baseUrl(); ?>/lib/core-2.0-SNAPSHOT.jar, <?= $this->baseUrl(); ?>/lib/javase-3.1.0.jar" 
        code="printer.AppletImpresionEncomienda.class" width=0 height=0>
<!--<div><p>El plugin de impresion java no esta instalado por favor instalelo</p></div>-->
</APPLET>
<div>
    <input type="hidden" id="selectedViaje" value="0"/>
    <input type="hidden" id="selectedBus" value="0"/>
    <input type="hidden" id="selectedHora" value="0"/>
    <input type="hidden" id="selectedDestino" value="0"/>
    <input type="hidden" id="selectedIdBus" value="0"/>
    <input type="hidden" id="<?= sha1("idUsuario") ?>" value="<?= base64_encode($session->person->identificador) ?>"/>
    <input type="hidden" id="<?= sha1("idSucursal") ?>" value="<?= base64_encode($session->sucursalName) ?>"/>
</div>
<div class="centroEncomienda">
    <div class="contenttab">
        <ul class="menutab">
            <li class="ui-widget-header itemtab"><a href="#" name="Recepcion">Recepcion</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Envio">Envio</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Arribo">Arribo</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Entrega">Entrega</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Equipaje">Equipaje</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Busqueda">Busqueda</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Clave">Clave</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Extracto">Extracto</a></li>
            <li class="ui-widget-header itemtab"><a href="#" name="Clientes">Clientes</a></li>
        </ul>
    </div>
   
    <div id="middleForm" class="block">
        <div class="contentBox height500"><?= new App_Form_Recepcion($this->sucursales, $this->ciudades, $this->baseUrl()) ?></div>
    </div>
    <button type="button" onclick="printJS('test/Encomiendas/public/sample.pdf')">
        Print PDF
    </button>
</div>

<!--<div id="print_v">-->
<div id="print_v" style="display: none;">
    <div style="max-width: 302px; min-width: 302px; width: 302px; border: 1px solid #000000; padding: 4px 8px;">
        <div class="pdf_head">
            <h3>{{empresa.title}}</h3>
            <p>Sucursal: {{cabecera.numeroSuc}}</p>
            <p>Telefono: {{cabecera.telefono}}</p>
            <p>{{cabecera.direccion}}</p>
            <p>({{cabecera.nombSuc}})</p>
            <p>{{cabecera.municipio}} - {{cabecera.ciudad}}</p>
            <h3>GUIA DE ENCOMIENDAS {{tipo}}</h3>
        </div>
        <div class="pdf_datos">
            <p><b>Fecha:</b> {{fechaActual}}</p>
            <p><b>Origen:</b> <span>{{encomienda.origen}}</span></p>
            <p><b>Destino:</b> <span>{{encomienda.destino}}</span></p>
            <p><b>Remitente:</b> <span>{{encomienda.remitente}}</span></p>
            <p><b>Telefono:</b> <span>{{encomienda.telefonoDestinatario}}</span></p>
            <p><b>Guia:</b> <span>{{encomienda.guia}}</span></p>
            <br>
            <table>
                <thead>
                <tr>
                    <th colspan="4"><b>DETALLE</b></th>
                </tr>
                <tr style="text-align: center;">
                    <th>Cant</th>
                    <th>Detalle</th>
                    <th>Peso</th>
                    <th>Mont</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="text-align: center">2</td>
                    <td>Cajas de ropa y material escritoio</td>
                    <td style="text-align: right;">5</td>
                    <td style="text-align: right;">55</td>
                </tr>
                <tr>
                    <td style="text-align: center;">1</td>
                    <td>Bolsa de zapatos y documentos</td>
                    <td style="text-align: right;">5</td>
                    <td style="text-align: right;">40</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4">Obs: {{encomienda.observacion}}</td>
                </tr>
                <tr>
                    <td colspan="3" style="text-align: right;"><p><b>TOTAL</b></p></td>
                    <td style="text-align: right;"><p><b>222</b></p></td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="pdf_pie">
            <p class="pie_usuario">Usuario: <span>{{cabecera.usuario}}</span></p>
            <br><br><br>
            <p class="pie_firma">-----------------------------------------</p>
            <p class="pie_firma"><b>{{encomienda.remitente}}</b></p>
        </div>
    </div>
</div>
<!--<div id="print_recibo_v">-->
<div id="print_recibo_v" style="display: none;">
    <div style="max-width: 302px; min-width: 302px; width: 302px; border: 1px solid #000000; padding: 4px 8px;">
        <div class="pdf_head">
            <h3>{{empresa.title}}</h3>
            <p>Sucursal: {{cabecera.numeroSuc}}</p>
            <p>Telefono: {{cabecera.telefono}}</p>
            <p>{{cabecera.direccion}}</p>
            <p>({{cabecera.nombSuc}})</p>
            <p>{{cabecera.municipio}} - {{cabecera.ciudad}}</p>
            <h3>RECIBO ENCOMIENDAS {{tipo}}</h3>
        </div>
        <div class="pdf_datos">
            <p><b>Fecha:</b> {{fechaActual}}</p>
            <p><b>Origen:</b> <span>{{encomienda.origen}}</span></p>
            <p><b>Destino:</b> <span>{{encomienda.destino}}</span></p>
            <p><b>Remitente:</b> <span>{{encomienda.remitente}}</span></p>
            <p><b>Telefono:</b> <span>{{encomienda.telefonoDestinatario}}</span></p>
            <p><b>Guia:</b> <span>{{encomienda.guia}}</span></p>
            <br>
            <table>
                <thead>
                <tr>
                    <th colspan="4"><b>DETALLE</b></th>
                </tr>
                <tr style="text-align: center;">
                    <th>Cant</th>
                    <th>Detalle</th>
                    <th>Peso</th>
                    <th>Mont</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="text-align: center">2</td>
                    <td>Cajas de ropa y material escritoio</td>
                    <td style="text-align: right;">5</td>
                    <td style="text-align: right;">55</td>
                </tr>
                <tr>
                    <td style="text-align: center;">1</td>
                    <td>Bolsa de zapatos y documentos</td>
                    <td style="text-align: right;">5</td>
                    <td style="text-align: right;">40</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4">Obs: {{encomienda.observacion}}</td>
                </tr>
                <tr>
                    <td colspan="3" style="text-align: right;"><p><b>TOTAL</b></p></td>
                    <td style="text-align: right;"><p><b>222</b></p></td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="pdf_pie">
            <p class="pie_usuario">Usuario: <span>{{cabecera.usuario}}</span></p>
            <br><br><br>
            <p class="pie_firma">-----------------------------------------</p>
            <p class="pie_firma"><b>{{encomienda.remitente}}</b></p>
        </div>
    </div>

</div>