<?php
$total = 0;
foreach ($this->datos['items'] as $key => $item){
    $total += $item['monto'];
}
?>
<style>
    @page { margin: 2px; }
    body { margin: 2px; }

    .pdf_main{
        width: 100%;
        padding: 5px;
        /*background-color: #1d5987;*/
    }
    .pdf_head{
        text-align: center;
    }

    .pdf_head h2{
        font-size: 14px;
    }

    .pdf_head h3{
        font-size: 12px;
    }

    .pdf_head p {
        font-size: 9px;
        padding: 2px 1px;
        margin: 0;
    }

    .pdf_datos p{
        font-size: 10px;
        padding: 2px 1px;
        margin: 0;
    }

    .pdf_detalle table{
        width: 100%;
        border-collapse: collapse;
    }

    .pdf_detalle table, th, td{
        border: 1px solid black;
    }

    .pdf_detalle table tbody tr td{
        font-size: 10px;
    }

    .pdf_detalle table tfoot tr td{
        font-size: 10px;
        font-weight: bold;
    }

    .quantum-print-h2 {
        font-size: 16px;
    }
</style>
<div class="pdf_main">
    <div class="pdf_head">
        <h3><?= $this->datos['empresa']['title']?></h3>
        <p>Sucursal: <?= $this->datos['cabecera']['numeroSuc'] ?></p>
        <p>Telefono: <?= $this->datos['cabecera']['telefono'] ?></p>
        <p><?= $this->datos['cabecera']['direccion'] ?></p>
        <p>(<?= $this->datos['cabecera']['nombSuc'] ?>)</p>
        <p><?= $this->datos['cabecera']['municipio'].' - '.$this->datos['cabecera']['ciudad'] ?></p>
        <?php if(0==0): ?>
        <h2 class="<?= App_Util_Statics::$fontH2; ?>">RECIBO DE ENTREGA</h2>
        <?php else: ?>
        <h2>RECIBO DE ENTREGA</h2>
        <?php endif; ?>
    </div>
    <div class="pdf_datos">
        <p><b>Fecha:</b> <?= 'sin fecha (no se de donde saca no esta en el json)' ?></p>
        <p><b>Origen:</b> <?= $this->datos['encomienda']['origen'] ?></p>
        <p><b>Destino:</b> <?= $this->datos['encomienda']['destino'] ?></p>
        <p><b>Remitente:</b> <?= $this->datos['encomienda']['remitente'] ?></p>
        <p><b>Destinatario:</b> <?= $this->datos['encomienda']['destinatario'] ?></p>
        <p><b>Telefono:</b> <?= $this->datos['encomienda'][']telefonoDestinatario'] ?></p>
        <p><b>Guia:</b> <?= $this->datos['encomienda']['guia'] ?></p>
    </div>
    <div class="pdf_detalle">
        <table>
            <thead>
            <tr>
                <th colspan="4" style="text-align: center; font-size: 12px"><b>DETALLE</b></th>
            </tr>
            <tr style="text-align: center;">
                <th style="font-size: 10px;">Cant</th>
                <th style="font-size: 10px;">Detalle</th>
                <th style="font-size: 10px;">Peso</th>
                <th style="font-size: 10px;">Mont</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->datos['items'] as $key => $item): ?>
                <tr>
                    <td style="text-align: center;"><?= $item['cantidad'] ?></td>
                    <td><?= $item['detalle'] ?></td>
                    <td style="text-align: right;"><?= $item['peso'] ?></td>
                    <td style="text-align: right;"><?= $item['monto'] ?></td>
                </tr>
            <?php endforeach; ?>
<!--            <tr>-->
<!--                <td style="text-align: center;">1</td>-->
<!--                <td>Sobre de documentos</td>-->
<!--                <td style="text-align: right;">1</td>-->
<!--                <td style="text-align: right;">10</td>-->
<!--            </tr>-->
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" style="font-size: 9px; font-weight: normal;"><?= $this->datos['encomienda']['observacion']?></td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: right; font-size: 10px;">TOTAL</td>
                <td style="text-align: right;"><?= $total ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
    <p style="font-size: 12px">Usuario: <?= $this->datos['cabecera']['usuario'] ?></p>
    <br>
    <br>
    <br>
    <p style="text-align: center;">-----------------------------------------</p>
    <p style="font-size: 12px; text-align: center"><?= $this->datos['encomienda']['remitente'] ?></p>
    <br>
    <p style="font-size: 8px; text-align: center;">Mobius IT Solutions</p>
</div>