<?php
$total = 0;
//foreach ($this->datos['items'] as $key => $item){
//    $total += $item['monto'];
//}
$destinosTem = array();
foreach ($this->datos['encomiendas'] as $key => $encomienda){
    array_push($destinosTem,$encomienda['destino']);
}
$destinos = array_unique($destinosTem);

$tiposTem = array();
foreach ($this->datos['encomiendas'] as $key => $encomienda){
    if(strcmp($encomienda['tipo'], 'POR PAGAR') != 0){
        $total = $total + $encomienda['total'];
    }
    array_push($tiposTem,$encomienda['tipo']);
}
//die($total);
$tipos = array_unique($tiposTem);

$arr_destinos1 = array();
foreach ($destinos as $destino) {
    $enc = array();
    foreach ($this->datos['encomiendas'] as $key => $encomienda){
        if(strcmp($encomienda['destino'], $destino) == 0){
            array_push($enc, $encomienda);
        }
    }
    if(count($enc) > 0){
        array_push($arr_destinos1, array('destino' => $destino, 'encomiendas' => $enc));
    }
}

$arr_final1 = array();
foreach ($arr_destinos1 as $adestino){
    $adestinos = array();
    foreach ($tipos as $tipo){
        $aEncomiendas = array();
        foreach ($adestino['encomiendas'] as $enc1){
            if(strcmp($tipo, $enc1['tipo']) == 0){
                array_push($aEncomiendas, $enc1);
            }
        }
        if(count($aEncomiendas) > 0){
            array_push($adestinos, array('tipo' => $tipo, 'encomiendas' => $aEncomiendas));
        }
    }
    if(count($adestinos) > 0){
        array_push($arr_final1, array('destino' => $adestino['destino'], 'tipos' => $adestinos) );
    }
}
//echo json_encode($arr_final1);
//die();
?>
<style>
    @page { margin: 2px; }
    body { margin: 2px; }

    .pdf_main{
        width: 100%;
        padding: 5px;
        /*background-color: #1d5987;*/
    }
    .pdf_head{
        text-align: center;
    }

    .t_detalle{
        width: 100%;
        border-collapse: collapse;
    }

    .t_detalle, .t_detalle th, .t_detalle td{
        border: 1px solid black;
    }

</style>
<div class="pdf_main">
    <div class="pdf_head">
        <h3 style="<?= App_Util_Statics::$printFontH3; ?>">MANIFIESTO DE ENVIO</h3>
        <h2 style="<?= App_Util_Statics::$printFontH2; ?>"><?= $this->nombreEmpresa->value ?></h2>
    </div>
    <div class="pdf_datos">
        <?php if(strlen($this->datos['manifiesto']['chofer']) > App_Util_Statics::$docPdfLimiteCaracteres): ?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Chofer:</b> <?= substr($this->datos['manifiesto']['chofer'], 0, App_Util_Statics::$docPdfLimiteCaracteres); ?></p>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><?= substr($this->datos['manifiesto']['chofer'], App_Util_Statics::$docPdfLimiteCaracteres, strlen($this->datos['manifiesto']['chofer'])-1) ?></p>
        <?php else:?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Chofer:</b> <?= $this->datos['manifiesto']['chofer'] ?></p>
        <?php endif;?>

        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Bus:</b> <?= $this->datos['manifiesto']['numBus'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destino:</b> <?= $this->datos['manifiesto']['destino'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Enviado por:</b> <?= $this->datos['cabecera']['usuario'] ?></p>
        <table style="width: 100%;">
            <tr>
                <td style="<?= App_Util_Statics::$printFontDatosP; ?> width: 50%;"><p><b>Fecha: </b><?= $this->datos['manifiesto']['fecha'] ?></p></td>
                <td style="<?= App_Util_Statics::$printFontDatosP; ?> width: 50%; text-align: right"><p><b>Hora:</b><?= $this->datos['manifiesto']['hora'] ?></p></td>
            </tr>
        </table>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?> text-align: center;">Fecha imp: <?= $this->fechaImpresion->format('Y-m-d H:i:s') ?></p>
    </div>
    <div class="pdf_detalle">
        <table class="t_detalle">
            <thead>
            <tr>
                <th colspan="3" style="text-align: center; <?= App_Util_Statics::$printFontTableHeadP; ?>"><b>DETALLE</b></th>
            </tr>
            <tr style="text-align: center;">
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Guia</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Detalle</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Mont</th>
            </tr>
            </thead>
            <tbody>


            <?php foreach ($arr_final1 as $destinos): ?>
                <tr>
                    <td colspan="3" style="text-align: center;"><h5 style="<?= App_Util_Statics::$printFontH5; ?> padding: 5px; margin: 0; background-color: #D1CDD8;"><?= $destinos['destino'] ?></h5></td>
                </tr>
                <?php foreach ($destinos['tipos'] as $tipos): ?>
                    <tr>
                        <td colspan="3" style="text-align: center;"><h5 style="font-size: 10px; padding: 5px; margin: 0;"><?= $tipos['tipo'] ?></h5></td>
                    </tr>
                    <?php foreach ($tipos['encomiendas'] as $encomienda1): ?>
                        <tr>
                            <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $encomienda1['guia'] ?></td>
                            <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $encomienda1['detalle'] ?></td>
                            <td style="<?= App_Util_Statics::$printFontTableBodyP; ?> text-align: right;"><?= $encomienda1['total'] ?></td>
                        </tr>
                        <?php //$total = $total + $encomienda['total'] ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>


            </tbody>
            <tfoot>
            <tr>
                <td colspan="2" style="text-align: right; <?= App_Util_Statics::$printFontTableFootP; ?>">TOTAL</td>
                <td style="text-align: right; <?= App_Util_Statics::$printFontTableFootP; ?>"><?= $total ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
    <br>
    <h5 style="<?= App_Util_Statics::$printFontH5; ?> text-align: center; padding: 5px; margin: 0;"><?= $this->datos['manifiesto']['chofer'] ?></h5>
    <h5 style="<?= App_Util_Statics::$printFontH5; ?> text-align: center; padding: 5px; margin: 0;">RECIBI CONFORME</h5>
    <p style="<?= App_Util_Statics::$printFontQuantumP; ?> font-size: 8px; text-align: center;">Mobius IT Solutions</p>
</div>