<?php
$total = 0;
foreach ($this->datos['items'] as $key => $item){
    $total += $item['monto'];
}
?>
<style>
    @page { margin: 2px; }
    body { margin: 2px; }

    .pdf_main{
        width: 100%;
        padding: 5px;
        /*background-color: #1d5987;*/
    }
    .pdf_head{
        text-align: center;
    }

    .pdf_detalle table{
        width: 100%;
        border-collapse: collapse;
    }

    .pdf_detalle table, th, td{
        border: 1px solid black;
    }
</style>
<div class="pdf_main">
    <div class="pdf_head">
        <h3 style="<?= App_Util_Statics::$printFontH3; ?>"><?= $this->datos['empresa']['title']?></h3>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>">Sucursal: <?= $this->datos['cabecera']['numeroSuc'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>">Telefono: <?= $this->datos['cabecera']['telefono'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><?= $this->datos['cabecera']['direccion'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>">(<?= $this->datos['cabecera']['nombSuc'] ?>)</p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><?= $this->datos['cabecera']['municipio'].' - '.$this->datos['cabecera']['ciudad'] ?></p>
        <h2 style="<?= App_Util_Statics::$printFontH2; ?>">RECIBO DE 123<?= $this->datos['encomienda']['tipo'] ?>123</h2>
    </div>
    <div class="pdf_datos">
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Fecha:</b> <?= $this->fechaImpresion->format('Y-m-d H:i:s') ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Origen:</b> <?= $this->datos['encomienda']['origen'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destino:</b> <?= $this->datos['encomienda']['destino'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Remitente:...</b> <?= $this->datos['encomienda']['remitente'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destinatario:</b> <?= $this->datos['encomienda']['destinatario'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Telefono:</b> <?= $this->datos['encomienda']['telefonoDestinatario'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Guia:</b> <?= $this->datos['encomienda']['guia'] ?></p>
    </div>
    <div class="pdf_detalle">
        <table class="t_detalle">
            <thead>
            <tr>
                <th colspan="4" style="text-align: center; <?= App_Util_Statics::$printFontTableHeadP; ?>"><b>DETALLE</b></th>
            </tr>
            <tr style="text-align: center;">
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Cant</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Detalle</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Peso</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Mont</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->datos['items'] as $key => $item): ?>
                <tr>
                    <td style="text-align: center; <?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $item['cantidad'] ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $item['detalle'] ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $item['peso'] ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $item['monto'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $this->datos['encomienda']['observacion']?></td>
            </tr>
            <tr>
                <td colspan="3" style="<?= App_Util_Statics::$printFontTableBodyP; ?>">TOTAL</td>
                <td style="text-align: right; <?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $total ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
    <p style="<?= App_Util_Statics::$printFontTableBodyP; ?>">Usuario: <?= $this->datos['cabecera']['usuario'] ?></p>
    <br>
    <p style="text-align: center;">-----------------------------------------</p>
    <p style="<?= App_Util_Statics::$printFontTableBodyP; ?> text-align: center"><?= $this->datos['encomienda']['remitente'] ?></p>
    <br>
    <p style="font-size: 8px; text-align: center;">Mobius IT Solutions</p>
</div>