<?php
$fechaActual = new DateTime();
$total = 0;
foreach ($this->datos['items'] as $key => $item){
    $total += $item['total'];
}
?>
<style>
    @page { margin: 2px; }
    body { margin: 2px; }

    .pdf_main{
        width: 100%;
        padding: 5px;
        /*background-color: #1d5987;*/
    }
    .pdf_head{
        text-align: center;
    }

    .pdf_detalle table{
        width: 100%;
        border-collapse: collapse;
    }

    .pdf_detalle table, th, td{
        border: 1px solid black;
    }

    .p-cabecera{
        margin: 2px;
        padding: 0;
    }
</style>
<div class="pdf_main">
    <div class="pdf_head">
        <h3 style="<?= App_Util_Statics::$printFontH3; ?>"><?= $this->datos['cabecera']['title'] ?></h3>
        <p style="<?= App_Util_Statics::$printFontCabeceraP; ?>">Sucursal: <?= $this->datos['cabecera']['numero'] ?> Telefono: <?= $this->datos['cabecera']['telefono'] ?></p>
        <p style="<?= App_Util_Statics::$printFontCabeceraP; ?>"><?= $this->datos['cabecera']['direccion'] ?></p>
        <p style="<?= App_Util_Statics::$printFontCabeceraP; ?>"><?= $this->datos['cabecera']['direccion2'] ?></p>
        <p style="<?= App_Util_Statics::$printFontCabeceraP; ?>"><?= $this->datos['cabecera']['ciudad'] ?></p>
        <br>
        <h2 style="<?= App_Util_Statics::$printFontH2; ?>"><?= (strcmp($this->datos['encomienda']['tipo'], 'DE ENTREGA') == 0)? 'RECIBO DE ENTREGA' : 'RECIBO DE ENTREGA POR  PAGAR' ?></h2>
    </div>
    <div class="pdf_datos">
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Fecha:</b> <?= $fechaActual->format('Y-m-d') ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Origen:</b> <?= $this->datos['encomienda']['origen'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destino:</b> <?= $this->datos['encomienda']['destino'] ?></p>

        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Entregado en:</b> <?= $this->datos['encomienda']['destino'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Guia:</b> <?= $this->datos['encomienda']['guia'] ?></p>

        <?php if(strlen($this->datos['encomienda']['remitente']) > App_Util_Statics::$docPdfLimiteCaracteres): ?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Remitente:</b> <?= substr($this->datos['encomienda']['remitente'], 0, App_Util_Statics::$docPdfLimiteCaracteres); ?></p>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><?= substr($this->datos['encomienda']['remitente'], App_Util_Statics::$docPdfLimiteCaracteres, strlen($this->datos['encomienda']['remitente'])-1) ?></p>
        <?php else:?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Remitente:</b> <?= $this->datos['encomienda']['remitente'] ?></p>
        <?php endif;?>

        <?php if(strlen($this->datos['encomienda']['destinatario']) > App_Util_Statics::$docPdfLimiteCaracteres): ?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destinatario:</b> <?= substr($this->datos['encomienda']['destinatario'], 0, App_Util_Statics::$docPdfLimiteCaracteres) ?></p>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><?= substr($this->datos['encomienda']['destinatario'], App_Util_Statics::$docPdfLimiteCaracteres, strlen($this->datos['encomienda']['destinatario'])-1) ?></p>
        <?php else:?>
            <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Destinatario:</b> <?= $this->datos['encomienda']['destinatario'] ?></p>
        <?php endif;?>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Recoje:</b> <?= $this->datos['infoEntrega']['receptor'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Documento:</b> <?= $this->datos['infoEntrega']['carnet'] ?></p>
        <p style="<?= App_Util_Statics::$printFontDatosP; ?>"><b>Telefono:</b> <?= $this->datos['encomienda']['telefonoRemitente'] ?></p>
    </div>
    <div class="pdf_detalle">
        <table>
            <thead>
            <tr>
                <th colspan="4" style="text-align: center; <?= App_Util_Statics::$printFontTableHeadP; ?>"><b>DETALLE</b></th>
            </tr>
            <tr style="text-align: center;">
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Cant</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Detalle</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Peso</th>
                <th style="<?= App_Util_Statics::$printFontTableHeadP; ?>">Mont</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->datos['items'] as $key => $item): ?>
                <tr>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?> text-align: center;"><?= $item['cantidad'] ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?>"><?= $item['detalle'] ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?> text-align: right;"><?= isset($item['peso'])? $item['peso'] : '0' ?></td>
                    <td style="<?= App_Util_Statics::$printFontTableBodyP; ?> text-align: right;"><?= $item['total'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" style="<?= App_Util_Statics::$printFontTableFootP; ?>"><?= $this->datos['encomienda']['observacion']?></td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: right; <?= App_Util_Statics::$printFontTableFootP; ?>">TOTAL</td>
                <td style="text-align: right; <?= App_Util_Statics::$printFontTableFootP; ?>"><?= $total ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
    <p style="<?= App_Util_Statics::$printFontDatosP; ?>">Usuario: <?= $this->datos['cabecera']['user'] ?></p>
    <br>
    <br>
    <br>
    <p style="<?= App_Util_Statics::$printFontDatosP; ?> text-align: center;">-----------------------------------------</p>
    <p style="<?= App_Util_Statics::$printFontDatosP; ?> text-align: center"><?= $this->datos['infoEntrega']['receptor'] ?></p>
    <br>
    <p style="font-size: 8px; text-align: center;">Mobius IT Solutions</p>
</div>